import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import kotlin.io.path.copyTo
import kotlin.io.path.createDirectories

abstract class GenerateFexGuestAssetsTask : DefaultTask() {
    @get:InputFile
    abstract val helloFixtureBinary: RegularFileProperty

    @get:InputFile
    abstract val metadataFile: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val output = outputDir.get().asFile.toPath()
        deleteRecursively(output)
        output.createDirectories()

        val helloDestination = output.resolve("payload").resolve("guest-tests").resolve("bin").resolve("hello_x86_64")
        helloDestination.parent.createDirectories()
        helloFixtureBinary.get().asFile.toPath().copyTo(helloDestination, overwrite = true)
        helloDestination.toFile().setExecutable(true, false)

        val metadataDestination = output.resolve("payload").resolve("config").resolve("fex-build-metadata.json")
        metadataDestination.parent.createDirectories()
        metadataFile.get().asFile.toPath().copyTo(metadataDestination, overwrite = true)

        writeUtf8(
            output.resolve("rootfs").resolve("usr").resolve("share").resolve("x360-v3").resolve("fex-baseline.txt"),
            "FEX baseline micro-rootfs generated by buildSrc\n",
        )
    }
}
